---
- hosts: vm2_web
  tasks: 
  - name: Install apache2 with php modules
    apt: 
      name: "{{ item }}"
    with_items:
    - apache2
    - php5
    - libapache2-mod-php5
    - php5-mcrypt
    - php5-mysql
    - php5-cli
    - wget

  - name: Enable mods
    apache2_module: name=rewrite state=present

  - name: Restart apache2
    service: name=apache2 state=restarted
